#!/bin/sh

# set up environment
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

# configuration
PROGRAM=kasworker
LOG=/var/log/kasworker.log
CMD=/opt/kooaba-worker/scripts/startsrv.sh
PIDFILE=/var/run/$PROGRAM.pid

. /lib/lsb/init-functions

case "$1" in
    start)
        echo "Starting $PROGRAM"
        start-stop-daemon -b --start --pidfile $PIDFILE \
            --exec $CMD 
        ;;
    stop)
        echo "Stopping $PROGRAM"
        start-stop-daemon --stop --pidfile $PIDFILE
        ;;
    restart)
        echo "Restarting $PROGRAM"
        start-stop-daemon --stop --pidfile $PIDFILE
        start-stop-daemon -b --start --pidfile $PIDFILE \
            --exec $CMD 
        ;;
    status)
        status_of_proc -p $PIDFILE $CMD
        ;;
    *)
        echo "Usage $PROGRAM {start|stop|restart|status}"
esac